# new line
add_newline = true

# right prompt
# right_format = """$cmd_duration"""

[character]
success_symbol = "[â¯](bold green)"
error_symbol = "[â¯](bold red)"
vicmd_symbol = "[â®](bold green)"

[cmd_duration]
min_time = 500
format = "took [$duration](bold yellow)"

[git_branch]
symbol = "ðŸŒ± "

[hostname]
ssh_only = true
format =  ">> [$hostname](bold cyan) "

[username]
format = "[$user]($style) "